### ISSUE TITLE
exception in one to one mapper

### ISSUE THREAD

**Issue by lakshankasun** [migdbdev/migdbclient#71]
`java.lang.NullPointerException
    at org.migdb.migdbclient.controllers.mapping.onetoone.OneToOneMap.oneToOneMapper(OneToOneMap.java:88)
    at org.migdb.migdbclient.views.modificationevaluator.ModificationEvaluator$1.handle(ModificationEvaluator.java:80)
    at org.migdb.migdbclient.views.modificationevaluator.ModificationEvaluator$1.handle(ModificationEvaluator.java:1)`

**Comment by Kanishkalahiru** [comment]
Bug fixed
